version: '3.8'

services:

  db:
    image: postgres:14
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    container_name: "db"
    environment:
      POSTGRES_DB: "library_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST: 127.0.0.1
    ports:
      - "5432:5432"
 
  back:
    container_name: "back"
    build:
      context: ./library_back
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./library_back:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  front:
    container_name: "front"
    build:
      context: ./library_front
    command: npm start
    stdin_open: true
    volumes:
      - ./library_front:/front
    ports:
      - "3000:3000"
    depends_on:
      - back
    links:
      - back
