version: '3.8'

services:

  db:
    image: postgres:14
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "library_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      #POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
    networks: 
      backend:
        ipv4_address: 127.0.0.2
    
 
  web:
    build:
      context: ./library_back
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
    volumes:
      - ./library_back:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks: 
      backend:
        ipv4_address: 127.0.0.4

networks: 
    backend:
      driver: "bridge"
      ipam:
        config:
            - subnet: 127.0.0.0/16
              gateway: 127.0.0.1
