version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
