name: CD

on:
  workflow_run:
    workflows: CI
    types:
      - completed

jobs: 
  deploy_front:
    name: Deploy Front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: "{{defaultContext}}:library_front"
          push: true
          tags: ${{ secrets.DOCKER_HUB_FRONT }}:latest
  deploy_back:
    name: Deploy Back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: "{{defaultContext}}:library_back"
          push: true
          tags: ${{ secrets.DOCKER_HUB_BACK }}:latest