name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_test:
    name: Build, Test and Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        touch library_back/.env
        echo POSTGRES_DB=${{ secrets.ENV_DB }} >> library_back/.env
        echo POSTGRES_USER=${{ secrets.ENV_USER }} >> library_back/.env
        echo POSTGRES_PASSWORD=${{ secrets.ENV_PASSWORD }} >> library_back/.env
        echo POSTGRES_PORT=${{ secrets.ENV_PORT }} >> library_back/.env
        echo POSTGRES_HOST=${{ secrets.ENV_HOST }} >> library_back/.env
        cat library_back/.env
    - name: Build
      run: docker-compose up -d
    - name: Run migrations
      run: | 
        docker-compose run back python manage.py makemigrations
        docker-compose run back python manage.py migrate
    - name: Test Backend
      run: docker-compose run back python manage.py test
    - name: Test Frontend
      run: docker-compose run front npm test
    - name: Lint Backend
      run: docker-compose run back flake8 --ignore=E501 --exclude=/backend/env
    - name: Lint Frontend
      run: docker-compose run front npx eslint .
      
  deploy:
    needs: build_test
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_HUB_REPOSITORY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
