name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        touch .env
        echo POSTGRES_DB=${{ secrets.ENV_DB }} >> .env
        echo POSTGRES_USER=${{ secrets.ENV_USER }} >> .env
        echo POSTGRES_PASSWORD=${{ secrets.ENV_PASSWORD }} >> .env
        echo POSTGRES_PORT=${{ secrets.ENV_PORT }} >> .env
        echo POSTGRES_HOST=${{ secrets.ENV_HOST }} >> .env
        cat .env
    - name: Build
      run: docker-compose up -d
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Frontend
      run: docker-compose run front npm test --watchAll=false
    - name: Test Backend
      run: docker-compose run back python manage.py test
