name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_test:
    name: Build, Test and Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        touch library_back/.env
        echo POSTGRES_DB=${{ secrets.ENV_DB }} >> library_back/.env
        echo POSTGRES_USER=${{ secrets.ENV_USER }} >> library_back/.env
        echo POSTGRES_PASSWORD=${{ secrets.ENV_PASSWORD }} >> library_back/.env
        echo POSTGRES_PORT=${{ secrets.ENV_PORT }} >> library_back/.env
        echo POSTGRES_HOST=${{ secrets.ENV_HOST }} >> library_back/.env
        cat library_back/.env
    - name: Build
      run: docker-compose up -d
    - name: Run migrations
      run: | 
        docker-compose run back python manage.py makemigrations
        docker-compose run back python manage.py migrate
    - name: Test Backend
      run: docker-compose run back python manage.py test
    - name: Test Frontend
      run: docker-compose run front npm test
    - name: Lint Backend
      run: docker-compose run back flake8 --ignore=E501 --exclude=/backend/env
    - name: Lint Frontend
      run: docker-compose run front npx eslint .
      
  deploy_front:
    needs: build_test
    name: Deploy Front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: "{{defaultContext}}:library_front"
          push: true
          tags: ${{ secrets.DOCKER_HUB_FRONT }}:latest
  deploy_back:
    needs: build_test
    name: Deploy Back
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: "{{defaultContext}}:library_back"
          push: true
          tags: ${{ secrets.DOCKER_HUB_BACK }}:latest
